# Authentication didn't work
# # .github/workflows/publish.yml
# name: Publish to pub.dev

# on:
#   push:
#     branches:
#     - main
# # Publish using custom workflow
# jobs:
#   publish:
#     permissions:
#       id-token: write # Required for authentication using OIDC
#     runs-on: ubuntu-latest
#     # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install dependencies
#         run: flutter pub get
#       - name: Publish
#         run: dart pub publish --force
